name: Terraform Destroy Staging

# This makes it a manual button in GitHub to prevent from accidentally destroying resources!
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  DestroyStaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::662829279164:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0
          terraform_wrapper: false

      # ------------------------------------------------------------------
      # STEP 1: DESTROY WEBSERVERS FIRST
      # ------------------------------------------------------------------
      # We must tear down webservers first because they depend on the database!
      # ------------------------------------------------------------------
      - name: Destroy Webservers
        run: |
          cd envs/stage/services/webservercluster
          terraform init -backend-config="backend.hcl"
          terraform destroy -auto-approve

      # ------------------------------------------------------------------
      # STEP 2: DESTROY THE DATABASE SECOND
      # ------------------------------------------------------------------
      - name: Destroy Database
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_db_username: "admin"
        run: |
          cd envs/stage/data-stores/mysql
          terraform init -backend-config="backend.hcl"
          terraform destroy -auto-approve
