name: Multi-Component Staging Deployment

# Only run the workflows on commit to the main branch
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  TerraformApply:
    runs-on: ubuntu-latest

     # THIS TELLS GITHUB TO RUN ALL COMMANDS INSIDE ENVS/STAGE FOLDER
    defaults:
      run:
        working-directory: ./envs/stage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # REPLACE THIS with your actual AWS Role ARN once created by Terraform
          role-to-assume: arn:aws:iam::662829279164:role/github-actions-terraform-role
          aws-region: us-east-1

      # Install Terraform on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0
          terraform_wrapper: false

      # ------------------------------------------------------------------
      # STEP 1: DEPLOY THE DATABASE FIRST (Dependency)
      # ------------------------------------------------------------------
      # The database must exist before the webservers boot up, otherwise 
      # the webserver remote state lookup tool will crash.
      # ------------------------------------------------------------------    

      - name: Initialize and Apply Database
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }} # Map secret securely
          TF_VAR_db_username: "admin" # Admin username can be hardcoded or set as a secret too
        run: |
          cd envs/stage/data-stores/mysql && terraform init -backend-config="backend.hcl"
          cd envs/stage/data-stores/mysql && terraform apply -auto-approve
      

      # ------------------------------------------------------------------
      # STEP 2: DEPLOY THE WEBSERVER CLUSTER SECOND
      # ------------------------------------------------------------------
      # Once the database successfully deploys, its state is pushed to S3. 
      # This step then reads that state file to bind the application cluster.
      # ------------------------------------------------------------------
      
      - name: Initialize and Apply Webservers
        run: |
          cd envs/stage/services/webserver-cluster && terraform init -backend-config="backend.hcl"
          cd envs/stage/services/webserver-cluster && terraform apply -auto-approve  
